# Kernel necessary : Python

## Python -> Txt

We will give some objets (vectors, matrices) from Python and we will write it in a txt file.

In [1]:
import numpy as np
import SaveLoadTxt as slt

path = "example_py.txt"

# 1. Julia-equivalent objects
A = np.arange(1.0, 7.0).reshape(2, 3)   # 2×3 Float64 matrix
v = np.arange(1, 5, dtype=np.int64)     # Int64 vector
s = np.pi                               # Float64 scalar
slt.dump_txt(path, [A, v, s], append=False)

# 2. Read back & verify
objs = slt.load_txt(path)
assert np.array_equal(objs[0], A)
assert np.array_equal(objs[1], v)
assert abs(objs[2] - s) < 1e-15
print("Round-trip OK for first three objects")

# 3. Append two more
v2 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
s2 = np.int64(42)
slt.dump_txt(path, [v2, s2], append=True)

Round-trip OK for first three objects


# Txt -> Python

We will read some objets (vectors, matrices) from the txt (from either Python or Julia code, the format in the txt is *""universal""*) and we will get it in Julia.

In [2]:
[A, v, s, v2, s2]

[array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([1, 2, 3, 4]),
 3.141592653589793,
 array([1.1, 2.2, 3.3]),
 np.int64(42)]

In [3]:
# 4. Reload and check all
all_objs = slt.load_txt(path)
assert len(all_objs) == 5
print("Append OK; total objects:", len(all_objs))


Append OK; total objects: 5


In [4]:
all_objs

[array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([1, 2, 3, 4]),
 3.141592653589793,
 array([1.1, 2.2, 3.3]),
 42]